name: terminal
description: The default xterm for dahliaOS

publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  xterm: ^4.0.0
  flutter_pty: ^0.4.1
  flutter_lints: ^5.0.0
  zenit_ui: 
    git: https://github.com/dahliaOS/zenit_ui.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
